<?php

function x() {
    $f = 2;
    $g = 3;
    
    try {
    
    } catch(Exception $e) {
        $e->message();
    } catch(Exception $f) {
        $e->message();
    }

}

function x2() {
    $e = 2;
}

?>